// <auto-generated />
namespace Club_De_Sport.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AttachUserToAdherent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AttachUserToAdherent));
        
        string IMigrationMetadata.Id
        {
            get { return "202005292339400_AttachUserToAdherent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
